#!/bin/bash

echo "==========================================="
echo "PTX Learning Path: From Basics to Expert GPU Kernel Engineering"
echo "==========================================="
echo ""
echo "This learning path is divided into five progressive modules:"
echo ""
echo "1. PTX-Basics          - Introduction to PTX syntax and basic concepts"
echo "2. PTX-Memory-Management - Memory spaces and optimization techniques"  
echo "3. PTX-Debugging-Profiling - Debugging tools and profiling methods"
echo "4. PTX-Advanced-Optimizations - Advanced optimization techniques"
echo "5. PTX-Custom-Kernels  - Complete custom kernel development"
echo ""
echo "Getting Started:"
echo "- Start with the PTX-Basics module"
echo "- Work through each module sequentially"
echo "- Complete exercises in each module"
echo "- Use debugging and profiling tools regularly"
echo ""
echo "Prerequisites:"
echo "- Basic C/C++ programming knowledge"
echo "- CUDA-capable GPU"
echo "- CUDA toolkit installed"
echo ""
echo "Essential Tools:"
echo "- nvcc, cuobjdump, nvdisasm"
echo "- Nsight Compute, Nsight Systems"
echo "- cuda-gdb, nvprof"
echo ""
echo "To begin, navigate to the PTX-Basics directory:"
echo "cd PTX-Basics/"
echo ""
echo "Happy learning!"
echo "==========================================="